### ISSUE TITLE
A problem during the "build FMF docker image" process

### ISSUE THREAD

**Issue by JayChan-USTC** [YoushaaMurhij/FMFNet#8]
Hello, I encountered a problem in the "build FMF docker image" process, I don't know how to do it, can you give me some solutions?

The problem is as follows:

Step 4/15 : RUN apt-get update  	&& apt-get install -y --no-install-recommends gsutil build-essential git ca-certificates python3-pip libboost-all-dev ffmpeg libsm6 libxext6   	&& rm -rf /var/lib/apt/lists/*
 ---> Running in dc951bdb8867
Get:1 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease [18.1 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:3 http://security.ubuntu.com/ubuntu focal-security ### InRelease [114 kB]
Get:4 http://ppa.launchpad.net/fish-shell/release-3/ubuntu focal InRelease [17.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:6 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal/main amd64 Packages [26.3 kB]
Get:7 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [30.1 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1,275 kB]
Get:11 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [1,183 kB]
Get:12 http://ppa.launchpad.net/fish-shell/release-3/ubuntu focal/main amd64 Packages [1,100 B]
Get:13 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:14 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [802 kB]
Get:15 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [628 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,086 kB]
Get:18 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [33.4 kB]
Get:19 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [679 kB]
Get:20 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1,636 kB]
Err:21 https://dl.bintray.com/tetrate/getenvoy-deb focal InRelease
  403  Forbidden [IP: 34.212.193.227 443]
Get:22 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [2,668 B]
Get:23 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [6,310 B]
Reading package lists...
E: Failed to fetch https://dl.bintray.com/tetrate/getenvoy-deb/dists/focal/InRelease  403  Forbidden [IP: 34.212.193.227 443]
E: The repository 'https://dl.bintray.com/tetrate/getenvoy-deb focal InRelease' is not signed.
The command '/bin/sh -c apt-get update  	&& apt-get install -y --no-install-recommends gsutil build-essential git ca-certificates python3-pip libboost-all-dev ffmpeg libsm6 libxext6   	&& rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by YoushaaMurhij** [comment]
Fixed in this commit  [0060c16](https://github.com/YoushaaMurhij/FMFNet/commit/0060c161c3972774ee1a552d03a4694a597e223e)
